### ISSUE TITLE
mount-support.c:  2 * cart before the horse ?

### ISSUE THREAD

**Issue by dcb314** [snapcore/snap-confine#131]
mount-support.c:362]: (style) Array index 'offset' is used before limits check.

mount-support.c:362]: (style) Array index 'offset' is used before limits check.

Suggest sanity check array indexes before use, not after.

**Comment by zyga** [comment]
Hello

Thank you for reporting this issue. Can you please tell which version/revision had this problem and which tool did you use to discover this?

**Comment by dcb314** [comment]
I found the bug in an earlier release (1.0.40 ?) and confirmed
it also exists in the current development source code, a few lines
further down.

I used a static analysis tool called cppcheck, available from sourceforge,
to find the bug. I find it a very useful tool for finding bugs in code.

**Comment by zyga** [comment]
Ah, I see, thanks. I've reproduced this and I'll fix it shortly

**Comment by zyga** [comment]
This is fixed in 281cadba059396a18651d9f0b4c85604ac87a408
