### ISSUE TITLE
cannot run other snap commands from a snap (even with devmode and connected plug/slot)

### ISSUE THREAD

**Issue by yphus** [snapcore/snap-confine#179]
The checkbox test-runner includes a couple of tests where we run other snaps commands.
With recent versions it stopped working and the common error msg is:

cannot open mount namespace file for namespace group tpm. errmsg: Permission denied

Here tpm is just because I was calling tpm commands, but hit the same msg with docker commands.

**Comment by triesz** [comment]
I hit the same with docker: https://github.com/docker-snap/docker/issues/3
Interestingly first execution is fine, error only appears from the second time on.

**Comment by zyga** [comment]
This is because of how we do namespace capture. I will fix this today.

**Comment by zyga** [comment]
This bug was moved to launchpad: https://bugs.launchpad.net/snap-confine/+bug/1644439
