### ISSUE TITLE
The calls for seccomp prevent Krita from running with nvidia

### ISSUE THREAD

**Issue by tseliot** [snapcore/snap-confine#35]
Bind mounting /var/lib/snapd/seccomp also seems to fail with this:
DEBUG: bind mounting /var/lib/snapd/seccomp to /tmp/snap.rootfs_TjFah9/var/lib/snapd/seccomp
cannot bind mount /var/lib/snapd/seccomp to /tmp/snap.rootfs_TjFah9/var/lib/snapd/seccomp. errmsg: No such file or directory

**Comment by zyga** [comment]
This bug is about loading seccomp profile (but not applying it) while we still have access to the real `/var/lib/snapd/seccomp/profiles`.
1. Load profile text
2. Do mount changes
3. Apply seccomp profile
4. Exec

**Comment by zyga** [comment]
I think this is fixed in 1.0.30
