### ISSUE TITLE
Snap-confine fails to pass checks if dmesg is root restricted

### ISSUE THREAD

**Issue by AlexNPavel** [snapcore/snap-confine#71]
For security reasons, my system only allows root to view dmesg, so 3 of the snap-confine tests fail with an "Operation not permitted" error. Is there a way the checks could be modified so this doesn't result in failures? Here is the test-suite.log:
/===============================================
   snap-confine 1.0.34: tests/test-suite.log
/===============================================

/# TOTAL: 19
/# PASS:  16
/# SKIP:  0
/# XFAIL: 0
/# FAIL:  3
/# XPASS: 0
/# ERROR: 0

.. contents:: :depth: 2

FAIL: test_complain_missed
/==========================

Test that near misses of complain fail./test_complain_missed: line 30: 15052 Bad system call         "$L" snap.name.app /bin/true 2> /dev/null
dmesg: read kernel buffer failed: Operation not permitted
: FAIL
FAIL test_complain_missed (exit status: 1)

FAIL: test_restrictions
/=======================

Test that seccomp filtering kills processes./test_restrictions: line 25: 15064 Bad system call         "$L" snap.name.app /bin/true 2> /dev/null
dmesg: read kernel buffer failed: Operation not permitted
: FAIL
FAIL test_restrictions (exit status: 1)

FAIL: test_unrestricted_missed
/==============================

Test that near misses of unrestricted fail./test_unrestricted_missed: line 30: 15166 Bad system call         "$L" snap.name.app /bin/true 2> /dev/null
dmesg: read kernel buffer failed: Operation not permitted
: FAIL
FAIL test_unrestricted_missed (exit status: 1)

**Comment by zyga** [comment]
Thanks for reporting this issue.

Those tests are on their way out. They are slowly replaced by unit tests and by real system tests powered by spread (see `spread-tests/`). My goal is to add real-system tests for various distributions to spread so that they can be executed on each commit. Spread sets up a VM and runs as root (we switch to particular users for testing user access but in general log access is unrestricted)

Can you please tell me which distribution you are using?

**Comment by AlexNPavel** [comment]
Sorry for the late response. I am currently using Arch Linux with AppArmor enabled, and the reason I had the build issues is because I was attempting to rebuild with apparmor enabled, which runs these tests. It is very easy to replicate the error if you want to. The method I am using is with tis security suggesstion on the Arch Wiki: https://wiki.archlinux.org/index.php/Security#Restricting_access_to_kernel_logs 
It should be possible to replicate on any system. You can also restrict dmesg with a kernel option if you have a grsec kernel. I am currently working around the problem by temporarily disabling the restriction and rebooting to build.

**Comment by zyga** [comment]
Thanks for reporting this.

There's still a long path before apparmor support on Arch can be fully enabled. This test is mostly harmless (you should look at `spread-tests` in the upstream repository for a replacement of those limited tests).

Currently the bigger issue is that not all of the apparmor kernel patches required to run snappy fully confined are in the upstream kernel. You'd have to cherry pick those patches from the snappy kernels. This link can be of some use perhaps: https://github.com/snapcore/sample-kernels

Canonical is aware of the issue and is working on upstreaming everything required. I suspect that in a few months all of the patches will be merged and various distributions will be able to enable required kernel configuration options to run a fully confined system

**Comment by drizzt** [comment]
You can try to use linux-lts-apparmor3 from AUR.
It's a linux-lts (4.4) kernel with apparmor3 patches taked from Ubuntu

**Comment by zyga** [comment]
I'm closing this for now as the project moved to github.com/snapcore/snapd
